# Generated by Django 2.2.5 on 2019-09-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190921_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='career_interest',
            field=models.CharField(choices=[('SC', 'Supply Chain'), ('OR', 'Operations Research'), ('MGMT', 'Operations Management'), ('DS', 'Data Science'), ('CNSLT', 'Management Consulting')], default='MGMT', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
