# Generated by Django 2.2.6 on 2019-11-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191112_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteeprofile',
            name='has_match',
            field=models.BooleanField(default=False, verbose_name='Match'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='at_capacity',
            field=models.BooleanField(default=False, verbose_name='MentorCapacity'),
        ),
    ]
